
# 项目配置文件

# web相关配置
http:
  host: 0.0.0.0
  port: 9000
  basicauth:
    user01: password01
    user02: password02
    user03: password03
  domains: # 能够调整sso的host列表
    - "api.codelieche.com"
    - "www.codelieche.com"
    - "app.codelieche.com"
    - "localhost"
    - "127.0.0.1"
    - "0.0.0.0"
# 数据库相关配置
database:
  mysql:
    host: "${MYSQL_HOST:127.0.0.1}"
    port: ${MYSQL_PORT:3306}
    user: "${MYSQL_USER:root}"
    password: "${MYSQL_PASSWORD}"
    database: "${MYSQL_DB_NAME:usercenter}"
  redis:
    host: "127.0.0.1:6379"
    clusters:
       - "127.0.0.1:6379"
    password: ""
    db: 0

# 是否为开发环境
debug: false